name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: dragonwell
        java-version: 11
    - name: gradle wrapper
      run: gradle wrapper
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: dragonwell
        java-version: 8
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: "7.3.3"
    
    - name: Build with Gradle
      run: ./gradlew build assembleRelease
