name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: setup gradle wrapper
      run: gradle wrapper --gradle-version 7.2.1
    - name: check dependencies
      run: ./gradlew dependencies
    - name: Build with Gradle
      run: ./gradlew build
